"""Integration tests using a real ENCODE gkm-SVM model (ENCFF579AOX).

The fixture is a 10-SV subset of ENCFF579AOX, an ATAC-seq enhancer
prediction model for hg38 from the Beer lab (JHU), using the default
LS-GKM parameters: kernel_type=gkm_esttrunc, L=11, k=7, d=3.

Oracle scores generated by Dongwon-Lee/lsgkm gkmpredict.
"""

import gzip
import random
from pathlib import Path

import pytest
import torch

from gkmsvm.codec import one_hot_encode, reverse_complement
from gkmsvm.importers.lsgkm import load_lsgkm_model, parse_lsgkm_header


FIXTURE = Path(__file__).parent.parent / "fixtures" / "encode_ENCFF579AOX_10sv.model.txt.gz"


@pytest.fixture
def model():
    return load_lsgkm_model(FIXTURE)


class TestEncodeModelHeader:
    def test_header_fields(self):
        h = parse_lsgkm_header(FIXTURE)
        assert h["kernel_type"] == "gkm_esttrunc"
        assert h["L"] == 11
        assert h["k"] == 7
        assert h["d"] == 3
        assert h["norc"] == 0
        assert h["nr_class"] == 2
        assert h["total_sv"] == 10


class TestEncodeModelLoad:
    def test_load(self, model):
        assert model.num_support_vectors == 10
        assert model.kernel_type == "gkm_esttrunc"
        assert model.bias == pytest.approx(-0.197343)

    def test_support_sequence_shape(self, model):
        assert model.support_sequences.shape == (10, 4, 300)

    def test_kernel_params(self, model):
        p = model.kernel_params
        assert p["L"] == 11
        assert p["k"] == 7
        assert p["d"] == 3
        assert p["include_rc"] is True


class TestEncodeModelInference:
    def test_score_random_sequence(self, model):
        torch.manual_seed(42)
        seq_len = 300
        idx = torch.randint(0, 4, (seq_len,))
        x = torch.zeros(4, seq_len)
        x[idx, torch.arange(seq_len)] = 1.0
        x = x.unsqueeze(0)

        score = model(x)
        assert score.shape == (1, 1)
        assert torch.isfinite(score).all()

    def test_score_support_vector(self, model):
        sv = model.support_sequences[0:1]
        score = model(sv)
        assert torch.isfinite(score).all()
        # The score should be nonzero since this SV has coefficient 1.0
        assert score.abs().item() > 0.01

    def test_rc_invariance(self, model):
        sv = model.support_sequences[0:1]
        sv_rc = reverse_complement(sv)
        score_fwd = model(sv)
        score_rc = model(sv_rc)
        assert torch.allclose(score_fwd, score_rc, atol=1e-4)

    def test_batch_scoring(self, model):
        batch = model.support_sequences[:3]
        scores = model(batch)
        assert scores.shape == (3, 1)
        assert torch.isfinite(scores).all()

    def test_chunked_matches_full(self, model):
        model_chunked = load_lsgkm_model(FIXTURE, sv_chunk_size=3)
        sv = model.support_sequences[0:1]
        score_full = model(sv)
        score_chunked = model_chunked(sv)
        assert torch.allclose(score_full, score_chunked, atol=1e-5)

    def test_variant_scoring(self, model):
        ref = model.support_sequences[0:1].clone()
        alt = ref.clone()
        # Mutate position 50: A -> C
        alt[0, :, 50] = 0
        alt[0, 1, 50] = 1  # C
        delta = model.score_variants(ref, alt)
        assert delta.shape == (1, 1)
        assert torch.isfinite(delta).all()

    def test_different_query_lengths(self, model):
        short = one_hot_encode("ACGTACGTACGTACGTACGT").unsqueeze(0)
        long = one_hot_encode("ACGT" * 50).unsqueeze(0)
        s1 = model(short)
        s2 = model(long)
        assert torch.isfinite(s1).all()
        assert torch.isfinite(s2).all()


class TestEncodeOracleScores:
    """Cross-validate against scores from Dongwon-Lee/lsgkm gkmpredict."""

    ORACLE = {
        "query_0": 0.944171,
        "query_1": 0.922764,
        "query_2": 0.977893,
        "random": -0.123703,
    }

    @pytest.fixture
    def queries(self):
        sv_seqs = []
        with gzip.open(FIXTURE, "rt") as f:
            in_sv = False
            for line in f:
                line = line.strip()
                if line.startswith("SV"):
                    in_sv = True
                    continue
                if not in_sv:
                    continue
                sv_seqs.append(line.split()[-1])
                if len(sv_seqs) >= 3:
                    break
        random.seed(42)
        rand_seq = "".join(random.choice("ACGT") for _ in range(300))
        return {
            "query_0": sv_seqs[0],
            "query_1": sv_seqs[1],
            "query_2": sv_seqs[2],
            "random": rand_seq,
        }

    def test_matches_gkmpredict(self, model, queries):
        for name, seq in queries.items():
            x = one_hot_encode(seq).unsqueeze(0)
            score = model(x).item()
            expected = self.ORACLE[name]
            assert score == pytest.approx(expected, abs=1e-4), (
                f"{name}: expected {expected}, got {score}"
            )
